# cloudbuild.yaml actualizado
steps:
  # 1. Construir la imagen usando el ID de ejecución de Cloud Build como tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nexus-legal-api:$BUILD_ID', '-t', 'gcr.io/$PROJECT_ID/nexus-legal-api:latest', '.']

  # 2. Subir la imagen
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nexus-legal-api:$BUILD_ID']

  # 3. Desplegar
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nexus-legal-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nexus-legal-api:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--service-account'
      - 'drive-sheets@ortega-473114.iam.gserviceaccount.com'
      - '--add-cloudsql-instances'
      - 'ortega-473114:us-central1:nexus-legal-db'
      
      # --- SECRETOS (Incluyendo el nuevo) ---
      - '--set-secrets'
      - 'CLICKUP_API_TOKEN=CLICKUP_API_TOKEN:latest,CLICKUP_WEBHOOK_SECRET=CLICKUP_WEBHOOK_SECRET:latest,CLICKUP_WEBHOOK_SECRET_ASSIGNMENTS=CLICKUP_WEBHOOK_SECRET_ASSIGNMENTS:latest'

      # --- VARIABLES DE ENTORNO ---
      - '--set-env-vars'
      - 'APP_ENV=production,LOG_LEVEL=INFO,CORS_ORIGINS=*'
      - '--set-env-vars'
      - 'DATABASE_URL=postgresql://nexus_user:nr5EPzU1fDQph1Kb*@/nexus_legal_db?host=/cloudsql/ortega-473114:us-central1:nexus-legal-db'
      - '--set-env-vars'
      - 'CLICKUP_TEAM_ID=31633845,CLICKUP_LIST_ID=901403238634'
      - '--set-env-vars'
      - 'CLICKUP_FIELD_ID_AI_LINK=3aa46502-0763-42d3-8cb9-71513566e3ae'
      
      # Recursos
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'

images:
  - 'gcr.io/$PROJECT_ID/nexus-legal-api:$BUILD_ID'