# ============================================================================
# Google Cloud Build Configuration - Nexus Legal API
# ============================================================================

steps:
  # --------------------------------------------------------------------------
  # Paso 1: Construir la imagen Docker
  # --------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/nexus-legal-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/nexus-legal-api:latest'
      - '.'

  # --------------------------------------------------------------------------
  # Paso 2: Subir la imagen al Container Registry
  # --------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/nexus-legal-api:$COMMIT_SHA'

  # --------------------------------------------------------------------------
  # Paso 3: Desplegar en Cloud Run
  # --------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nexus-legal-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nexus-legal-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      
      # --- SECRETOS (Desde Secret Manager) ---
      - '--set-secrets'
      - 'CLICKUP_API_TOKEN=CLICKUP_API_TOKEN:latest,CLICKUP_WEBHOOK_SECRET=CLICKUP_WEBHOOK_SECRET:latest'

      # --- VARIABLES DE ENTORNO (Consolidadas desde tu final_env.yaml) ---
      - '--set-env-vars'
      - 'APP_ENV=production'
      - '--set-env-vars'
      - 'DEBUG=true'
      - '--set-env-vars'
      - 'LOG_LEVEL=INFO'
      - '--set-env-vars'
      - 'CORS_ORIGINS=*'
      
      # Configuración ClickUp
      - '--set-env-vars'
      - 'CLICKUP_TEAM_ID=31633845'
      - '--set-env-vars'
      - 'CLICKUP_LIST_ID=901403238634'  # ID Confirmado (Home List)
      - '--set-env-vars'
      - 'CLICKUP_TRIGGER_CONDICIONAL=Link Intake'
      - '--set-env-vars'
      - 'CLICKUP_FIELD_ID_AI_LINK=3aa46502-0763-42d3-8cb9-71513566e3ae'
      
      # Configuración Google Sheets
      - '--set-env-vars'
      - 'GOOGLE_SHEETS_ENABLED=true'
      - '--set-env-vars'
      - 'GOOGLE_SHEETS_SPREADSHEET_ID=161uBv2YTWOiR-82zlsf6ANbiqtfiow8B4x62VXCTPwU'
      - '--set-env-vars'
      - 'GOOGLE_SHEETS_SHEET_NAME=logs'
      - '--set-env-vars'
      - 'GOOGLE_SHEETS_FIELD_MAPPING={"task_id": 1, "task_name": 2, "status": 3, "link_intake": 4, "url": 5}'
      
      # Configuración Dispatch Externo
      - '--set-env-vars'
      - 'EXTERNAL_DISPATCH_ENABLED=true'
      - '--set-env-vars'
      - 'EXTERNAL_DISPATCH_URL=https://enqueuer-api-907757756276.us-central1.run.app/enqueue'
      - '--set-env-vars'
      - 'EXTERNAL_DISPATCH_CALLBACK_BASE_URL=https://nexus-legal-api-223080314602.us-central1.run.app'
      
      - '--set-env-vars'
      - 'FILTROS_API_KEY=tu-api-key-real'  # <--- ASEGÚRATE DE CAMBIAR ESTO POR LA LLAVE REAL ANTES DE SUBIR

      # Configuración de Recursos
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'

images:
  - 'gcr.io/$PROJECT_ID/nexus-legal-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/nexus-legal-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY