# ============================================================================
# Google Cloud Build Configuration
# Construye imagen Docker y la despliega en Cloud Run
# ============================================================================

steps:
  # Paso 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/nexus-legal-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/nexus-legal-api:latest'
      - '.'

  # Paso 2: Push imagen a Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/nexus-legal-api:$COMMIT_SHA'

  # Paso 3: Deploy a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nexus-legal-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nexus-legal-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'  # Cambiar según tu región
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # Cambiar a --no-allow-unauthenticated si requieres auth
      - '--set-env-vars'
      - 'APP_ENV=production'
      - '--set-secrets'
      - 'CLICKUP_API_TOKEN=CLICKUP_API_TOKEN:latest,CLICKUP_WEBHOOK_SECRET=CLICKUP_WEBHOOK_SECRET:latest,DATABASE_URL=DATABASE_URL:latest'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:REGION:INSTANCE_NAME'  # Reemplazar con tu instancia Cloud SQL
      - '--min-instances'
      - '0'  # Scale to zero
      - '--max-instances'
      - '10'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'

images:
  - 'gcr.io/$PROJECT_ID/nexus-legal-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/nexus-legal-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY
